name: github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc
    steps:  
    - uses: actions/checkout@v2
    - name: Running the build
      run: make
     


    
